// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1 - ROS 2',
      items: [
        'module-1/ros2-intro',
        'module-1/ros2-nodes-services',
        'module-1/ros2-topics-actions',
        'module-1/ros2-projects',
        'module-1/ros2-advanced-concepts',
        'module-1/ros2-testing-debugging',
        'module-1/ros2-performance-optimization',
        'module-1/ros2-integration-patterns',
        'module-1/urdf-modeling',
        'module-1/ai-agent-integration',
        'module-1/ros2-mini-projects',
      ],
    },
    {
      type: 'category',
      label: 'Module 2 - Digital Twin',
      items: [
        'module-2/gazebo-physics',
        'module-2/unity-rendering',
        'module-2/sensor-integration',
        'module-2/digital-twin-projects',
        'module-2/digital-twin-advanced-concepts',
        'module-2/digital-twin-real-time-sync',
        'module-2/digital-twin-analytics',
        'module-2/digital-twin-case-studies',
        'module-2/lidar-simulation',
        'module-2/depth-camera-simulation',
        'module-2/imu-simulation',
        'module-2/data-export-ai-training',
        'module-2/digital-twin-mini-projects',
      ],
    },
    {
      type: 'category',
      label: 'Module 3 - AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3/isaac-sim-intro',
        'module-3/getting-started-isaac-sim',
        'module-3/photorealistic-simulation-synthetic-data',
        'module-3/introduction-isaac-ros',
        'module-3/three-d-perception-pipelines',
        'module-3/isaac-perception',
        'module-3/isaac-navigation',
        'module-3/isaac-projects',
        'module-3/isaac-advanced-vslam',
        'module-3/isaac-manipulation-control',
        'module-3/isaac-learning-methods',
        'module-3/isaac-system-integration',
      ],
    },
    {
      type: 'category',
      label: 'Module 4 - Vision-Language-Action (VLA)',
      items: [
        'module-4/introduction',
        'module-4/voice-to-text-whisper',
        'module-4/llm-cognitive-planning',
        'module-4/ros2-action-execution-pipeline',
        'module-4/vision-object-understanding',
        'module-4/vla-mini-project',
        'module-4/whisper-setup',
        'module-4/whisper-examples',
        'module-4/llm-planning',
        'module-4/llm-integration',
        'module-4/execution-systems',
        'module-4/ros2-execution',
        'module-4/vision-perception',
        'module-4/vision-examples',
        'module-4/action-examples',
        'module-4/planning-examples',
        'module-4/quickstart',
        'module-4/task-runner-example',
        'module-4/task-runner-code',
        'module-4/vla-fundamentals',
        'module-4/vla-projects',
        'module-4/vla-advanced-models',
        'module-4/vla-training-methods',
        'module-4/vla-robotics-applications',
        'module-4/vla-future-directions',
        'module-4/capstone-project',
        'module-4/capstone-workflow',
      ],
    },
  ],
};

export default sidebars;